### ISSUE TITLE
Console printing and lifetimes

### ISSUE THREAD

**Issue by Meziu** [Meziu/ctru-rs#15]
>I reset it to the state before rebasing. To be honest this only reinforces to me the idea that the Drop implementation isn't the way to go. We should either go the "print method" route, or find another way to fix this, like initliazing the defaultConsole in ctru::init (edit: we can't do this second option either because it must be the user to initialize Gfx, making the whole Console implemenetations unusable until then. With this knowledge, I believe we should also require to pass the Gfx object to Console to be sure the Console init won't crash)

Written by me in #14.

@AzureMarker let's talk here about this.

Priority is for no crashes to be caused from `safe` code the user may write. This would be best to solve with support for `println!` and other "printing" functions, since we can't limit access to `std` code.

**Comment by Meziu** [comment]
Oh wow. Ok, most of my problems were due to a misconception of Rust's panic code. While panic handling (mainly with `r#try`) is above the binary's `main`, the panic backtrace print isn't. This means both gfx and Consoles still exist by that point, and nothing is dropped yet (as you can see in this image).

![image](https://user-images.githubusercontent.com/55318903/148826664-e083fcd3-7768-4ba9-8827-a89b2d3afb5b.png)
 
So, if we are sure a Console exists, we can just print directly, can't we?

**Comment by AzureMarker** [comment]
Where we can't statically guarantee things, like gfx is initialized before console, we can use panics. This way we avoid scarier ARM exceptions or undefined behavior.

**Comment by Meziu** [comment]
True, I guess, at least we can notify the user of any wrong-doings. Still, about the `Gfx` thing, look at #16. I believe requiring a `gfx` reference or something is needed, there is no reason to make a Console before gfx (since it uses gfx framebuffers and crashes if the service wasn't enabled).

**Comment by AzureMarker** [comment]
> Written by me in #14.

I don't see this quote, so maybe it's a bad link?

> I reset it to the state before rebasing.

I read this as you added back the Drop impl, but I don't see it. For soundness we need _something_ to happen when the Console drops so we don't let libctru have a dangling pointer.
