### ISSUE TITLE
Require service dependencies

### ISSUE THREAD

**Issue by Meziu** [Meziu/ctru-rs#16]
This is tied to my tangent on #15.

`Console::init` depends on the existence of a `Gfx` istance, and thus should require it. Finding all "dependant" services and fixing this issue is necessary.

AFAIK other than `Console` depending on `gfx`, it's just the `applets` that depend on `apt`

**Comment by Meziu** [comment]
Also, the `Gfx` struct is void, so we may implement `Send` on it, if we want to go the "reference on Console init" route.

**Comment by Meziu** [comment]
The `Console::init` requiring Gfx has been fixed in https://github.com/Meziu/ctru-rs/commit/d51bdcf972881f15e6f6074a2ed667cad46446cc. Weirdly enough, it isn't required to keep a pointer to Gfx or do any lifetimes tricks, since (after testing) I noticed printing when the `Gfx` instance is dropped simply does nothing.

**Comment by Meziu** [comment]
Turns out applets do call `apt` functions, but not `apt` service initialization is required (they are possibly direct OS calls).
Also, I fixed the examples in https://github.com/Meziu/ctru-rs/commit/d021da0c6f9402d0caee6f589f689d707a4c4691, so this issue is now closed.

**Comment by AzureMarker** [comment]
> Weirdly enough, it isn't required to keep a pointer to Gfx or do any lifetimes tricks, since (after testing) I noticed printing when the `Gfx` instance is dropped simply does nothing.

We need to use [`PhantomData`](https://doc.rust-lang.org/stable/std/marker/struct.PhantomData.html) to achieve this. I can make a PR.
