### ISSUE TITLE
liblinker_fix_3ds.a and libpthread_3ds.a

### ISSUE THREAD

**Issue by AzureMarker** [Meziu/ctru-rs#2]
Where did these files come from? Can they be generated/compiled instead of committed?

**Comment by Meziu** [comment]
https://github.com/Meziu/pthread-3ds

https://github.com/Meziu/rust-linker-fix-3ds

**Comment by AzureMarker** [comment]
I'm trying to find some way to include them in the build explicitly instead of passing around the compiled outputs. The issue is that lots of things need to use their symbols (ex. std for pthread) and Cargo doesn't link crates to each other unless they specify a dependency. Hence the static lib approach. But maybe there's another way?

**Comment by Meziu** [comment]
Originally I wanted to include the definitions into ctru-rs, but quickly noticed the compiler didn't accept C definitions from inside the crate, so I had to link them as C libraries instead. I don't think there is much to do (other than make a build script or something, though I don't know how that would work for a crate imported from cargo, which is the ultimate goal of this project).

**Comment by AzureMarker** [comment]
I was able to get it narrowed down to the following missing symbols after adding the crates as dependencies and implementing the workaround for https://github.com/rust-lang/rust/issues/47384 (adding an empty function to the crates and calling it in main):
```
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/11.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/arm-none-eabi/lib/armv6k/fpu/libc.a(lib_a-sysfstat.o): in function `fstat':
(.text.fstat+0x24): undefined reference to `_fstat_r'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/11.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/arm-none-eabi/lib/armv6k/fpu/libc.a(lib_a-syslseek.o): in function `lseek':
(.text.lseek+0x30): undefined reference to `_lseek_r'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/11.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/arm-none-eabi/lib/armv6k/fpu/libc.a(lib_a-sysopen.o): in function `open':
(.text.open+0x2c): undefined reference to `_open_r'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/11.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/arm-none-eabi/lib/armv6k/fpu/libc.a(lib_a-sysread.o): in function `read':
(.text.read+0x2c): undefined reference to `_read_r'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/11.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/arm-none-eabi/lib/armv6k/fpu/libc.a(lib_a-sysstat.o): in function `stat':
(.text.stat+0x24): undefined reference to `_stat_r'
```

Weirdly there are no missing symbols when using the binary `.a` files directly via build script, so I'm not sure why these are missing when linking via Cargo dependency.

**Comment by Meziu** [comment]
This are symbols present in other libraries, i think. Check if you are correctly linking everything mentioned in the ctru-rs build script.

**Comment by Meziu** [comment]
Getting `pthread_3ds` to be imported, just like `linker-fix-3ds` did, is vital to keep the project clean (no duplicating `std`), and to have less error prone linking. This may even fix [horizon-std #2](https://github.com/Meziu/rust-horizon/issues/2#) for all I know.

**Comment by Meziu** [comment]
I've made small changes in `ctru` and `cargo-3ds`:

ctru-rs: https://github.com/Meziu/ctru-rs/commit/049af1f6e831982578e7c941cc5287a0966184d1
cargo-3ds: https://github.com/Meziu/cargo-3ds/commit/f542cb10d67dbe31350aa7c0dde6765c16cbfd57

These should be fixing the issue with `_open_r` and those other non-linked symbols. The fix was very stupid, but I've lazily never looked into it. Dunno how `pthread_3ds` linked before tbh, but it doesn't matter.

@AzureMarker sorry to be asking directly, but could you do the magic trick you did with `linker_fix_3ds`? I've tried replicating the workaround but I didn't quite understand how it works. Thank you.

**Comment by AzureMarker** [comment]
> Making `pthread_3ds` a `#![no_std]` crate is shortsighted and an useless effort, since it would require a `GlobalAlloc`ator and panic handling, such that would go in contrast with the `std` ones used by the rest of the project, rendering useless the division in the first place.

I agree, though I'd use less strong language (it's good to consider the idea at the very least). It'll be nice and useful to have it as a regular cargo dependency.

> @AzureMarker sorry to be asking directly, but could you do the magic trick you did with `linker_fix_3ds`? I've tried replicating the workaround but I didn't quite understand how it works. Thank you.

No problem, I should be able to open a PR for that soon. Thanks for working on this and doing so much!

**Comment by Meziu** [comment]
I am thanking you. You saved this project from near death, even though it still has so much potential. Thank you.
