### ISSUE TITLE
Test threading

### ISSUE THREAD

**Issue by Meziu** [Meziu/ctru-rs#26]
All of the "environmental" `std::thread` features (like Mutex, LocalKeys and such) work in single threaded programs, but we never tested actually spawning threads. In the remote eventuality they work, we should implement them via `pthread-3ds` and possibly remove the `thread` module here in `ctru`. 

@AzureMarker

**Comment by AzureMarker** [comment]
The thread module has some 3ds specific APIs, like controlling which core the thread spawns into (important for a few reasons).

**Comment by Meziu** [comment]
> The thread module has some 3ds specific APIs, like controlling which core the thread spawns into (important for a few reasons).

Should we instead use only that one, then?

**Comment by Meziu** [comment]
Ported the `thread-basic` example from `libctru` in https://github.com/Meziu/ctru-rs/commit/5bdb0a4db1ecab43b6364507803913ea4d443730.

There is an issue I noticed while testing: the `ctru::init` hook for panicking actually blocks the threads since it runs for every single one. While I enjoy seeing the `Mutex`s working, this is a problem with the required input. Maybe taking a button input isn't the best way to do this.

**Comment by AzureMarker** [comment]
> There is an issue I noticed while testing: the `ctru::init` hook for panicking actually blocks the threads since it runs for every single one.

Not quite sure what you mean by this. Do you mean the other threads don't execute while it waits for the button press?

**Comment by Meziu** [comment]
Yes, that too. But I also meant that taking input for each thread on panic isn't great. Though probably the biggest issue arises when no Console is present, since the HID will wait for an input but the user won't see the error message telling him to press select.
