### ISSUE TITLE
Printing makes the program crash if no Console was selected

### ISSUE THREAD

**Issue by Meziu** [Meziu/ctru-rs#3]
Maybe we should default to the first Console created, or have a method to auto-select while building a Console object.
@AzureMarker, if you want to, you can help on this easy issue. I will find a fix eventually anyways, so don't worry.

**Comment by AzureMarker** [comment]
I was able to replicate the crash by using `Console::default` without a call to `select`.

I have a separate fork of ctru-rs based on the upstream (https://github.com/AzureMarker/ctru-rs), which retains the `ctru-sys` package. Do you mind if we follow that approach instead of this separate git history? Or I can make the fix in both repositories.

**Comment by AzureMarker** [comment]
This is kind of weird, because this example implies that printing should work immediately after initializing graphics and console:
https://libctru.devkitpro.org/app_launch_2source_2main_8c-example.html

**Comment by AzureMarker** [comment]
Oh I know why, we move the console object after the initialization. Since libctru holds a pointer to the console the pointer gets invalidated when we move the console into the struct, so it crashes if the pointer isn't refreshed.

**Comment by Meziu** [comment]
I'd keep this git history, it's based on vivlim's after all. As for the bug, good job! Happy to be helped😄

**Comment by AzureMarker** [comment]
What I mean is this (your) git repo is fresh, with no connection to vivlim or rust3ds' repos (there is only one commit in the graph). That means we can't open a PR to either with this repo. My repo is based on rust3ds with some fixes from vivlim's repo, so it could be used as the basis for a PR. Plus it keeps the history and structure.

I'll open a PR on this repo in the meantime though.

**Comment by AzureMarker** [comment]
Opened https://github.com/Meziu/ctru-rs/pull/4
