### ISSUE TITLE
See the error message on panic!

### ISSUE THREAD

**Issue by Meziu** [Meziu/ctru-rs#9]
While looking in the panic system for the Rust runtime, I noticed the `std::panic::set_hook` function. This would be very useful to obtain debug info on panicking (since the exit is instantaneous right now), maybe even with button input to quit. This should be implemented in `ctru_rs::init`. Giving it other uses justifies it's existence, especially at the eyes of newcomers.

**Comment by Meziu** [comment]
@AzureMarker this issue should be easy enough for me to work on it alone. If you have any spare time, could you please test the filesystem related stuff? The SD alone is fine, but maybe heading off into `romfs` territory would be good. I haven't had the time to do this myself, yet.

**Comment by AzureMarker** [comment]
Sure, I opened #11

**Comment by Meziu** [comment]
RWLocks are used in the `std::panic::take_hook` and a write there causes a deadlock. So this will stay on hold until https://github.com/Meziu/pthread-3ds/issues/3 is fixed ig.

**Comment by Meziu** [comment]
Fixed in https://github.com/Meziu/ctru-rs/commit/22404a9f145eee6c1d68ae129ea827f09c592ba7.
@AzureMarker debugging is a joy now :smile:

**Comment by AzureMarker** [comment]
The panic messages look really good!
